const SOURCE_DATA = {
  version: 2,
  store: "내 카페",
  sales: [],
  purchases: [],
  payroll: [],
  comparisons: {},
  monthlyExtras: {},
  weeks: {},
  inventory: [],
  checks: [],
  lastBackup: null,
  importedAt: null,
  sourceVersion: "public-v1",
  employment: {
    hireDate: null,
    weeklyHours: null,
    holidayDay: null,
    firstWeek: null,
    endDate: null,
    normalDays: 5.0,
    rates: {},
    start: "2026-10-01",
    end: "2027-09-30",
    threshold: 15.0,
    capHours: 8.0,
    maxWeekly: 40.0,
    averageWeeks: 4.0,
  },
  sourceControls: {},
  incomes: [],
};
/** @returns {import("./contracts/legacy.ts").LegacyLedger} */
export const seed = () => structuredClone(SOURCE_DATA);
